---
language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.4"
  - PUPPET_VERSION="~> 4.0.0"
  - PUPPET_VERSION="~> 4.1.0"
  - PUPPET_VERSION="~> 4.2.0"
  - PUPPET_VERSION="~> 4.3.0"
  - PUPPET_VERSION="~> 4"
  - PUPPET_VERSION="~> 4" STRICT_VARIABLES="yes"
